version: 2
jobs:
  build:
      docker:
        - image: circleci/android:api-27-alpha
      working_directory: ~/code
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - run:
            name: Assemble build
            command: ./gradlew :TMessagesProj:assembleArmv7AppSpectorDebug
        - run:
            name: Upload to HockeyApp
            command: sh ./.circleci/hockeyapp-upload.sh
            environment:
                APK_PATH: app/build/outputs/apk/debug/TMessagesProj-armv7-appSpector-debug.apk