version: 2
jobs:
  build:
      docker:
        - image: bitriseio/android-ndk:v2018_06_02-18_55-b1029
      working_directory: ~/code
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - run: git submodule init
        - run: git fetch --recurse-submodules
        - run:
            name: Assemble build
            command: ./gradlew :TMessagesProj:assembleArmv7AppSpectorDebug
        - run:
            name: Upload to HockeyApp
            command: sh ./.circleci/hockeyapp-upload.sh
            environment:
                APK_PATH: app/build/outputs/apk/debug/TMessagesProj-armv7-appSpector-debug.apk